package cn.kuroneko.demos.user.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * 对应表: test_user 用户
 */
@ApiModel("用户")
@Data
public class UserDTO {
    /**
     * 字段: id 主键
     */
    @ApiModelProperty(value = "id 主键", dataType = "Long", required = true)
    private Long id;

    /**
     * 字段: name 姓名
     */
    @ApiModelProperty(value = "姓名", dataType = "String", required = true)
    private String name;

    /**
     * 字段: salary 薪水
     */
    @ApiModelProperty(value = "薪水", dataType = "Double", required = true)
    private BigDecimal salary;

    /**
     * 字段: age 年龄
     */
    @ApiModelProperty(value = "年龄", dataType = "int", required = true)
    private Integer age;

    /**
     * 字段: groupId 用户所属组织
     */
    @ApiModelProperty(value = "用户所属组织", dataType = "Long", required = true)
    private Long groupId;

    /**
     * 字段: createTime 创建时间
     */
    private Date createTime;
}