eureka:
  instance:
    #【默认为false】优先使用内网IP，避免配置本地host
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
    #【默认为30秒】eureka客户端间隔多久去拉取服务注册信息
    registry-fetch-interval-seconds: 3
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false