eureka:
  instance:
    #【默认为false】优先使用内网IP，避免配置本地host
    prefer-ip-address: true
  client:
    serviceUrl:
  #   8001是在k8s中暴露的svc的port
  # 如果是在虚拟机中，则应当为运行的实际端口，即18001
      defaultZone: http://eureka-server-node1:8001/eureka/,http://eureka-server-node2:8001/eureka/,http://eureka-server-node3:8001/eureka/
    #【默认为30秒】eureka客户端间隔多久去拉取服务注册信息
    registry-fetch-interval-seconds: 3
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false