package cn.kuroneko.demos.user.entity;

import lombok.Data;

/**
 * This class was generated by MyBatis Generator.
 * 对应表: test_group 组织
 */
@Data
public class GroupDO {
    /**
     * 字段: id 主键
     */
    private Long id;

    /**
     * 字段: groupName 组织名称
     */
    private String groupName;
}